name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install backend dependencies
      run: npm ci
    
    - name: Install frontend dependencies
      run: cd client && npm ci
    
    - name: Run backend tests
      run: npm test
      env:
        CI: true
    
    - name: Run frontend tests
      run: cd client && npm test
      env:
        CI: true
    
    - name: Build frontend
      run: cd client && npm run build
      env:
        CI: true
    
    - name: Lint backend code
      run: npx eslint . --ext .js
    
    - name: Lint frontend code
      run: cd client && npx eslint . --ext .js,.jsx